### ISSUE TITLE
It does not compile - NuGet/assembly references seem to be broken/missing

### ISSUE THREAD

**Issue by luminescent** [rikace/AkkaActorModel#1]
Hi 

I had to manually fix a lot of the projects as the library references were broken. Most of the work is around changing some references that point to hard-coded paths to NuGet references. I could make a pull request for this?

**Comment by rikace** [comment]
Sure thanks

I did the same this week end, most of the projects were referencing local dlls and not NuGet.

Thanks again
Riccardo

**Comment by luminescent** [comment]
I have submitted the pull request. (Nice Akka tutorial, by the way!)

**Comment by rikace** [comment]
Super!

Thank you very much!!
